/******************************************************************************
 *Module: ultra-sonic sensor
 *
 * File Name: ultrasonic.h
 *
 * Description: ultra-sonic driver header file
 *
 * Date Creation: 16/10/2021
 *
 * Author: Youssef Abdel Aziz
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define ULTRASONIC_ECHO_PORT_ID      PORTD_ID
#define ULTRASONIC_ECHO_PIN_ID	     PIN6_ID
#define ULTRASONIC_TRIGGER_PORT_ID	 PORTB_ID
#define ULTRASONIC_TRIGGER_PIN_ID	 PIN5_ID

#define SOUND_WAVE_AIR 340
/*******************************************************************************/
/*
 * Description:Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the
 *  GPIO driver
 */
void Ultrasonic_init(void);
/*
 * Description:Send the Trigger pulse to the ultra-sonic.
 */
void Ultrasonic_Trigger(void);
/*
 * Description:Send the trigger pulse by using Ultrasonic_Trigger function.
* Start the measurements by the ICU from this moment.
* Return: The measured distance in Centimeter*/
uint16 Ultrasonic_readDistance(void);
/*
 * Description: This is the call back function called by the ICU driver.
* This is used to calculate the high time (pulse time) generated by
* the ultra-sonic sensor.*/
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
